# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0003_auto_20171022_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='name',
            new_name='username',
        ),
    ]
