# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0005_subscriber_joined_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='joined_in',
        ),
    ]
