# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(upload_to='img')),
                ('img2', models.FileField(upload_to='img')),
            ],
        ),
    ]
